"""Markdown -> styled PDF -> GCS upload for the Publisher & Governance Agent."""

from __future__ import annotations

import datetime as dt
import io
import os

from .telemetry import get_logger

_REPORT_CSS = """
@page { size: A4; margin: 2.2cm 1.8cm; }
body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; font-size: 10.5pt; line-height: 1.5; }
h1 { color: #0b3d2e; border-bottom: 2px solid #0b3d2e; padding-bottom: 6px; font-size: 20pt; }
h2 { color: #12604a; margin-top: 22px; font-size: 14pt; }
h3 { color: #1a1a1a; font-size: 12pt; }
table { border-collapse: collapse; width: 100%; margin: 10px 0 16px 0; }
th { background: #12604a; color: #fff; text-align: left; padding: 6px 8px; font-size: 9.5pt; }
td { border: 1px solid #d8d8d8; padding: 6px 8px; font-size: 9.5pt; vertical-align: top; }
tr:nth-child(even) td { background: #f4f7f6; }
code, pre { font-family: 'Courier New', monospace; background: #f2f2f2; padding: 1px 4px; border-radius: 3px; }
.risk-high { color: #b3261e; font-weight: bold; }
.risk-medium { color: #a86a00; font-weight: bold; }
.risk-low { color: #12604a; font-weight: bold; }
.footer-note { color: #777; font-size: 8pt; margin-top: 24px; }
"""


def markdown_to_pdf_bytes(markdown_text: str, title: str = "Change Impact Assessment") -> bytes:
    """Render a Markdown report into a styled PDF, returned as bytes."""
    import markdown as md_lib

    html_body = md_lib.markdown(
        markdown_text, extensions=["tables", "fenced_code", "toc"]
    )
    html_document = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{title}</title></head>
<body>{html_body}
<p class="footer-note">Generated by the Change Impact Analysis Agent on
{dt.datetime.now(dt.timezone.utc).isoformat()}Z.</p>
</body>
</html>"""

    try:
        from weasyprint import CSS, HTML

        pdf_bytes = HTML(string=html_document).write_pdf(
            stylesheets=[CSS(string=_REPORT_CSS)]
        )
        return pdf_bytes
    except ImportError:
        # Fall back to xhtml2pdf when weasyprint's native deps aren't available.
        from xhtml2pdf import pisa

        styled = f"<style>{_REPORT_CSS}</style>{html_document}"
        buffer = io.BytesIO()
        pisa.CreatePDF(src=styled, dest=buffer)
        return buffer.getvalue()


def upload_pdf_to_gcs(
    pdf_bytes: bytes,
    issue_number: int,
    bucket_name: str | None = None,
    signed_url_expiration_minutes: int = 10080,
) -> str:
    """Upload the PDF report to GCS and return a downloadable URL.

    Returns a v4 signed URL when service-account credentials support signing;
    otherwise returns the ``gs://`` URI plus a note that a signed URL could
    not be generated in this environment.
    """
    logger = get_logger()
    bucket_name = bucket_name or os.environ.get("REPORTS_GCS_BUCKET")
    if not bucket_name:
        raise ValueError(
            "No GCS bucket configured. Set REPORTS_GCS_BUCKET or pass bucket_name explicitly."
        )

    blob_path = f"impact-reports/{issue_number}.pdf"
    gcs_uri = f"gs://{bucket_name}/{blob_path}"

    from google.cloud import storage

    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    blob.upload_from_string(pdf_bytes, content_type="application/pdf")

    try:
        signed_url = blob.generate_signed_url(
            version="v4",
            expiration=dt.timedelta(minutes=signed_url_expiration_minutes),
            method="GET",
        )
        logger.info("Uploaded impact report to %s and generated signed URL.", gcs_uri)
        return signed_url
    except Exception as exc:  # noqa: BLE001 - signing requires a service-account key
        logger.warning(
            "Could not generate a signed URL (%s); returning gs:// URI instead.", exc
        )
        return gcs_uri


def publish_report_pdf(
    markdown_text: str,
    issue_number: int,
    bucket_name: str | None = None,
    title: str = "Change Impact Assessment",
) -> str:
    """Convenience wrapper: markdown -> PDF -> GCS upload -> URL."""
    pdf_bytes = markdown_to_pdf_bytes(markdown_text, title=title)
    return upload_pdf_to_gcs(pdf_bytes, issue_number=issue_number, bucket_name=bucket_name)
